### ISSUE TITLE
pmu_io_domains Ethernet configuration error

### ISSUE THREAD

**Issue by Daniel-zhan-itead** [darkxst/ha-operating-system#40]
We recently found that there is a problem with the configuration in this project (0023-dts-pmu_io_domain-set-wifi-to-3.3v.patch) which may cause potential permanent damage to the Ethernet functionality. Please correct it.
![lQLPKGzzsRXEBCvNASvNAd-wa-zd2iqopLcF1hckOP_MAA_479_299](https://github.com/darkxst/ha-operating-system/assets/54268313/fd6cba47-cb23-4fab-ab83-6f3da8a9e3bf)

**Comment by darkxst** [comment]
I don’t know if there are difference in the upstream kernel drivers here, however if I set vccio5-supply to vcc3v3_sd then the MAC fails to communicate with PHY (see below error). This is presumably why I have kept this set on vcc_1v8. Unfortunately the RTL8201F datasheet does not provide any information on the RMII signalling voltages. Phy-supply is correctly set to vcc_3v3 though.

```
 808.047071] rk_gmac-dwmac ffc40000.ethernet eth0: __stmmac_open: Cannot attach to PHY (error: -19)
```

**Comment by chrismarine74** [comment]
If i understand preferably when you define vcc 1v8 does it mean 1.8v power supply? and 3v3 3.3v ? how is it possible for something that works with a lower voltage than normal design to get damaged?

**Comment by freezingzz** [comment]
> If i understand preferably when you define vcc 1v8 does it mean 1.8v power supply? and 3v3 3.3v ? how is it possible for something that works with a lower voltage than normal design to get damaged?

The power supply is determined by the hardware not by this configuration, and this configuration only sets up some pull-up resistors or MOS tube matches in the IO to make the IO suitable for operation in this voltage range.

Incorrect matching will cause IO damage in use, resulting in distortion of the output waveform - we have proved this through comparative experiments, and we have replicated the damage to the IO port on the device running this HAOS. Rockchip officials have also confirmed that this incorrect configuration will definitely cause hardware damage - it is just a matter of time and probability.

**Comment by darkxst** [comment]
> The power supply is determined by the hardware not by this configuration, and this configuration only sets up some pull-up resistors or MOS tube matches in the IO to make the IO suitable for operation in this voltage range.

Can you explain then why setting vccio5 to 3v3 completely disables ethernet on the upstream kernel? If I ship an update with this setting, it will completely disable ethernet for **ALL USERS**.

>  808.047071] rk_gmac-dwmac ffc40000.ethernet eth0: __stmmac_open: Cannot attach to PHY (error: -19)

**Comment by chrismarine74** [comment]
the official configuration of the original sonoff operating system what settings it has adopted, maybe copying it will solve the problem, unless the integrated design io is wrong

**Comment by darkxst** [comment]
> the official configuration of the original sonoff operating system what settings it has adopted, maybe copying it will solve the problem, unless the integrated design io is wrong

They are using the downstream Rockchip kernel, which apart from being old, diverges quite significantly from the mainline upstream kernel that is used in HAOS. That being said I have mostly the same Device tree at least as far as ethernet configuration. Underlying drivers however will be different.

**Comment by astangcong** [comment]
倒闭算了， 我现在对你们这个设备和系统失望透顶了。弄个设备当玩具吧，别做智能家居系统了

**Comment by darkxst** [comment]
@astangcong I am not employed or paid by Sonoff. I provide these builds in my spare time so that other users can enjoy HAOS.

**Comment by astangcong** [comment]
可是当初sonoff宣传的是可以刷系统，而且给的是这个项目地址，具体你们内部是如何的我也管不着了，反正我也不打算用了

**Comment by darkxst** [comment]
@astangcong go complain to Sonoff on their forums then.

**Comment by chrismarine74** [comment]
is there anything newer regarding the ethernet port malfunction issue?
the company sent me a new device to replace the previous one that gave an ethernet, failure I'm waiting to see if a solution has finally been given from itead and if it really was a problem of the haos. that has been excellent work 
I believe that sonoff has some mistake in the design of the product and now he is trying to collect it

**Comment by darkxst** [comment]
I do not yet have any updates on a solution to this. Nor have iTead provided any assistance on this. I will try again to find some solution when updating to the 12.2 release.

**Comment by fredofm** [comment]
Hi all,

I think I'm facing the same eth0 issue. It's not usable anymore and the only solution I have is to use a usb ethernet device.

No problem to use that workaround and I would like to take the opportunity to say thank you for your great work @darkxst . We all know that it's something you do for free :)

In my case I think the eth0 stops working in the middle of a HA core update, I guess that something was corrupted and after that HA is not working fine anymore (updates take too much time or fail, I have to restart several times until all services connect properly, sometimes backups section is not available, ....) so I decided to flash again the sd card with image [haos_ihost-12.0.rc1.img.xz](https://github.com/darkxst/ha-operating-system/releases/download/12.0.rc1/haos_ihost-12.0.rc1.img.xz) and start it from scratch but using the usb ethernet device instead.

But after seeing the waiting screen for a while (http://homeassistant.local), it ends with the following error:

> .900 ERROR (MainThread) [asyncio] Task exception was never retrieved
> future: .sync_property_change() done, defined at /usr/src/supervisor/supervisor/utils/dbus.py:217> exception=DBusInterfaceError('D-Bus object /org/freedesktop/NetworkManager/ActiveConnection/13766 is not usable, introspection is missing required properties interface')>
> Traceback (most recent call last):
> File "/usr/src/supervisor/supervisor/utils/dbus.py", line 235, in sync_property_change
> await update(changed)
> File "/usr/src/supervisor/supervisor/dbus/network/interface.py", line 160, in update
> await self.connection.connect(self.dbus.bus)
> File "/usr/src/supervisor/supervisor/dbus/interface.py", line 95, in connect
> await super().connect(bus)
> File "/usr/src/supervisor/supervisor/dbus/interface.py", line 49, in connect
> await self.initialize(await DBus.connect(bus, self.bus_name, self.object_path))
> File "/usr/src/supervisor/supervisor/dbus/interface.py", line 103, in initialize
> raise DBusInterfaceError(
> supervisor.exceptions.DBusInterfaceError: D-Bus object /org/freedesktop/NetworkManager/ActiveConnection/13766 is not usable, introspection is missing required properties interface
> .913 ERROR (MainThread) [asyncio] Task exception wa...

I tried to boot it again from the original ihost image but it's not working (remove the maskrom pins soldering) and it keeps the red light forever and there is not network activity (I tried hard reset as well).

Could you help me to solve the issue?. Currently it's a nice brick.

**Comment by darkxst** [comment]
It may help to provide NetworkManager configuration file for the usb ethernet. These can be installed on CONFIG usb drive (you will need a hub so you can also have ethernet plugged in!)

https://github.com/home-assistant/operating-system/blob/dev/Documentation/configuration.md

It uses standard Network Manager config files, for which there should be plenty of references online.

**Comment by vladimird** [comment]
any news about ETH issue?

**Comment by brooqs** [comment]
I think there is no any news. Unfortunately my sonoff dead as rat. 100 usd is flying away. Too expensive experience for me. Anyway thanks for the advanture.

**Comment by luaartist** [comment]
was wondering about the SD Card perhaps something to do with the spike when having Z2M running and perhaps clocking  higher speed than anticipated for the model completely. Thinking of a SSD solution is on my mind. As for not being a programmer this is only an idea. [https://www.mouser.com/ProductDetail/Murata-Electronics/LBEE0ZZ1WE-uSD-M2?qs=sGAEpiMZZMv0NwlthflBi8sW3mpDMWDOQpgxxGL3HsA%3D](url) an SD to M2 that can perhaps debug and figure out what the issues are. One day I will test it. For now the TP-Link usb3.0 to RJ45 Gigabit would be ideal. Just not sure if the 2.0USB stock can do the trick with a stock driver for the USB. A BLE adapter seems to fit the bill since it will run too much power in its modified condition.  The idea of making the device entirely a slave so that its functions can be utilized as a smart coordinator is a dream worth having at the moment.

**Comment by fabianoarruda** [comment]
>  For now the TP-Link usb3.0 to RJ45 Gigabit would be ideal. Just not sure if the 2.0USB stock can do the trick with a stock driver for the USB. 

@luaartist Just so you know, I've been running mine for months now using a cheap Usb 2.0 to Gigabit adapter from AliExpress, based on ASIX AX88178. It's natively supported, so I didn't need to install any drivers.

**Comment by guslma** [comment]
any news about ETH issue?

**Comment by Mec0808** [comment]
Dopo aver provato HA in modalità eWeLink CUBE non si connette più ad internet collegamento LAN, qualcuno è riuscito a riprogrammare la LAN e farla rifunzionare?

Grazie mille

**Comment by vladimird** [comment]
No. mine is osle burned but almost any usb to ehternet adpter is recognised and works.
